// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWebSearchPackageString = "e0f5e73b-70f7-4045-acd7-844989b64f81";
        public static Guid guidWebSearchPackage = new Guid(guidWebSearchPackageString);

        public const string guidWebSearchPackageCmdSetString = "768141fe-b8e5-4f94-9c2a-809403e8f215";
        public static Guid guidWebSearchPackageCmdSet = new Guid(guidWebSearchPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SearchCommandId = 0x0100;
    }
}