// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DisplayInfoBar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDisplayInfoBarPackageString = "84459e9e-025c-4c6f-a9cd-982c33f6d642";
        public static Guid guidDisplayInfoBarPackage = new Guid(guidDisplayInfoBarPackageString);

        public const string guidDisplayInfoBarPackageCmdSetString = "982557fc-20bc-4fbb-af50-4c8e43fdae51";
        public static Guid guidDisplayInfoBarPackageCmdSet = new Guid(guidDisplayInfoBarPackageCmdSetString);

        public const string guidImagesString = "9723cfbc-1e11-4315-b371-a54e62578d6d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InforBarToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}